-- =============================================
-- Seed: levels 1-60 with tier (README 2. Sistema de Niveis e Faixas)
-- 1-10: pleasant, 11-20: painful, 21-30: death,
-- 31-40: hell, 41-50: paradise, 51-60: reality
-- =============================================

INSERT INTO public.levels (id, tier) VALUES
  (1, 'pleasant'),
  (2, 'pleasant'),
  (3, 'pleasant'),
  (4, 'pleasant'),
  (5, 'pleasant'),
  (6, 'pleasant'),
  (7, 'pleasant'),
  (8, 'pleasant'),
  (9, 'pleasant'),
  (10, 'pleasant'),
  (11, 'painful'),
  (12, 'painful'),
  (13, 'painful'),
  (14, 'painful'),
  (15, 'painful'),
  (16, 'painful'),
  (17, 'painful'),
  (18, 'painful'),
  (19, 'painful'),
  (20, 'painful'),
  (21, 'death'),
  (22, 'death'),
  (23, 'death'),
  (24, 'death'),
  (25, 'death'),
  (26, 'death'),
  (27, 'death'),
  (28, 'death'),
  (29, 'death'),
  (30, 'death'),
  (31, 'hell'),
  (32, 'hell'),
  (33, 'hell'),
  (34, 'hell'),
  (35, 'hell'),
  (36, 'hell'),
  (37, 'hell'),
  (38, 'hell'),
  (39, 'hell'),
  (40, 'hell'),
  (41, 'paradise'),
  (42, 'paradise'),
  (43, 'paradise'),
  (44, 'paradise'),
  (45, 'paradise'),
  (46, 'paradise'),
  (47, 'paradise'),
  (48, 'paradise'),
  (49, 'paradise'),
  (50, 'paradise'),
  (51, 'reality'),
  (52, 'reality'),
  (53, 'reality'),
  (54, 'reality'),
  (55, 'reality'),
  (56, 'reality'),
  (57, 'reality'),
  (58, 'reality'),
  (59, 'reality'),
  (60, 'reality')
ON CONFLICT (id) DO NOTHING;
